### ISSUE TITLE
A tiny setup question

### ISSUE THREAD

**Issue by Jason-Guo1999** [Luzifer/staticmap#1]
Hi Luzifer, I'm truly impressed with your work. However, I've encountered an issue while running the 0.5.0 release. I tried sending the JSON file from the example as a part of a GET request to the service's URL, but I keep receiving a 404 error code. Have you come across this issue before? Any guidance would be greatly appreciated. Thank you for your time and assistance.

**Comment by Luzifer** [comment]
- The JSON is supposed to be `POST`ed to `/map.png` (documented in [API -> Overlay Support](https://github.com/Luzifer/staticmap#overlay-support)).
- `GET` requests are made to `/map.png` using the parameters documented here: [API](https://github.com/Luzifer/staticmap#api)

**Comment by Jason-Guo1999** [comment]
So the 404 error code is generated by illegal requests? I'm wondering if I correctly run the service. Could you please give me more details about it? Thank you for your time and assistance.

**Comment by Luzifer** [comment]
Sounds more like you've sent an request to something else than `/map.png` or `/status`. Those are the only supported paths.

**Comment by Jason-Guo1999** [comment]
Thanks I've figured the GET out .However It reports this when I sending the JSON file from the example as a part of a POST request to /map.png：
2023/10/14 19:10:53 Error downloading tile file: error 404: tile not found
time="2023-10-14T19:10:53Z" level=error msg="Map render failed: error 404: tile not found (Request: /map.png)"

**Comment by Luzifer** [comment]
That error was caused by the OpenFireMap not serving blank tiles for tiles without data but returning `HTTP 404` for those. I've updated the generator library which gained a workaround for this behavior in the meantime. A new release will be available shortly.
